### ISSUE TITLE
2.0.3 crashes with minicraft.saveload.Load.loadPrefs error

### ISSUE THREAD

**Issue by africalinguist** [chrisj42/minicraft-plus-revived#25]
OS: Ubuntu 16.04

Game Version: 2.0.3 official

Error:

Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: 1
	at minicraft.saveload.Load.loadPrefs(Load.java:317)
	at minicraft.saveload.Load.<init>(Load.java:101)
	at minicraft.Game.init(Game.java:250)
	at minicraft.Game.run(Game.java:1140)
	at java.lang.Thread.run(Thread.java:748)

**Comment by chrisj42** [comment]
Delete your preferences files in APPDATA/roaming/playminicraft/mods/Minicraft_Plus/
you can leave the saves/ folder intact, don't delete it. Just delete the two files, Preferences.miniplussave and Unlocks.miniplussave.

Then try running 2.0.4 instead, as that's the newer version.

**Comment by chrisj42** [comment]
oh geez, whoops, you even said you were running Ubuntu. Sorry, then it would be in ~/.playminicraft/mods/Minicraft_Plus/

**Comment by chrisj42** [comment]
Any luck?

**Comment by africalinguist** [comment]
deleting .playminicraft/mods/Minicraft_Plus/ fixed it!
