### ISSUE TITLE
Server does not allow going up stairs without kermiting suicide

### ISSUE THREAD

**Issue by lockness-Ko** [chrisj42/minicraft-plus-revived#42]
```
java.lang.NullPointerException
	at minicraft.saveload.Load.loadEntity(Load.java:548)
	at minicraft.saveload.Load.loadEntity(Load.java:517)
	at minicraft.network.MinicraftClient.parsePacket(MinicraftClient.java:286)
	at minicraft.network.MinicraftConnection.run(MinicraftConnection.java:76)
```

thats the error. pls fix thx

**Comment by lockness-Ko** [comment]
The latest version

**Comment by lockness-Ko** [comment]
2.0.4

**Comment by chrisj42** [comment]
that's not actually the latest version, it's just the latest non-prerelease. You ought to be using 2.0.5-dev3

**Comment by chrisj42** [comment]
if the bug persists there let me know

**Comment by lockness-Ko** [comment]
K will do

**Comment by africalinguist** [comment]
any news? If this has been fixed the issue should be closed.

**Comment by lockness-Ko** [comment]
Sorry I thought it was already closed! All good now.

Thanks

**Comment by chrisj42** [comment]
still not closed lol. I'll do it.
